server:
  port: 0
spring:
  kafka:

    bootstrap-servers:
    - 43.200.43.104:9092
    - 43.200.43.104:19092
    - 43.200.43.104:29092
    consumer:

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      auto-offset-reset: earliest